package com.example.tvd.customer_info.values;

public class ConstantValues {
    public static final int REGISTRATION_SUCCESS = 1;
    public static final int REGISTRATION_FAILURE = 2;
    public static final int LOGIN_SUCCESS = 3;
    public static final int LOGIN_FAILURE = 4;
    public static final int SEARCH_FOUND = 5;
    public static final int SEARCH_NOT_FOUND = 6;
    public static final int INSERTION_SUCCESSFULL = 7;
    public static final int INSERTION_FAILURE = 8;
    public static final int CONNECTION_TIME_OUT = 9;
    public static final int SWITCH_CONSUMER_SUCCESS = 10;
    public static final int SWITCH_CONSUMER_FAILURE = 11;
    public static final int DEACTIVATE_ACCOUNT = 12;
    public static final int ACCOUNT_DEACTIVATED_SUCCESSFULLY = 13;
    public static final int ACCOUNT_DEACTIVATION_FAILURE = 14;
    public static final int VIEW_BILL_SUCCESS = 15;
    public static final int VIEW_BILL_FAILURE = 16;
    public static final int SMS_SEND_SUCCESS = 17;
    public static final int SMS_SEND_FAILURE = 18;
    public static final int EMAIL_SEND_SUCCESS = 19;
    public static final int EMAIL_SEND_FAILURE = 20;
    public static final int PASSWORD_CHANGED_SUCCESS =21;
    public static final int PASSWORD_CHANGED_FAILURE =22;
    public static final int ACCOUNT_ID_SEARCH_SUCCESS = 23;
    public static final int ACCOUNT_ID_SEARCH_FAILURE = 24;
    public static final int COMPLAINT_REGISTER_SUCCESS = 25;
    public static final int COMPLAINT_REGISTER_FAILURE = 26;
    public static final int COMPLAINT_HISTORY_SUCCESS = 27;
    public static final int COMPLAINT_HISTORY_FAILURE = 28;
    public static final int LT_BILLING_SUMMARY_SUCCESS = 29;
    public static final int LT_BILLING_SUMMARY_FAILURE = 30;
    public static final int BILLING_FRAGMENT_SUCCESS = 31;
    public static final int BILLING_FRAGMENT_fAILURE = 32;
    public static final int COLLECTION_FRAGMENT_SUCCESS = 33;
    public static final int COLLECTION_FRAGMENT_FAILURE = 34;
    public static final int LAST_PAYMENT_DATE_SUCCESS = 35;
    public static final int LAST_PAYMENT_DATE_FAILURE = 36;
}
